# Use the official MongoDB image from Docker Hub
FROM mongo:7.0.4-rc0

# Set environment variables for admin credentials
ENV MONGO_INITDB_ROOT_USERNAME=meister
ENV MONGO_INITDB_ROOT_PASSWORD=lemon123!@#

# Optionally, you can specify a port for MongoDB (27017 is the default)
EXPOSE 27017