apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseflix-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roseflix-backend
  template:
    metadata:
      labels:
        app: roseflix-backend
    spec:
      containers:
      - name: roseflix-backend-cont
        image: public.ecr.aws/z2m4y8s8/dp1001:roseflix-backend-prod
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: "roseflix-mongodb://meister:lemon123%21%40%23@roseflix-mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: roseflix-backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  # Use NLB
spec:
  selector:
    app: roseflix-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
