apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseflix-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roseflix-frontend
  template:
    metadata:
      labels:
        app: roseflix-frontend
    spec:
      containers:
      - name: roseflix-frontend-cont
        image: 671231939531.dkr.ecr.us-east-1.amazonaws.com/dp1001:roseflix-frontend-prod
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_KEY  # not relevant anymore but you can still see the env var get applied on the linux container
          valueFrom:
            secretKeyRef:
              name: frontend-moviedb-key
              key: MOVIEDB_KEY
        resources:
          limits:
            memory: 530Mi
            cpu: 780m
      #nodeSelector:
        #node-type: t2small
---
apiVersion: v1
kind: Service
metadata:
  name: roseflix-frontend-service
spec:
  selector:
    app: roseflix-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
