apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseflix-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roseflix-mongodb
  template:
    metadata:
      labels:
        app: roseflix-mongodb
    spec:
      containers:
      - name: roseflix-mongodb-cont
        image: public.ecr.aws/z2m4y8s8/dp1001:roseflix-mongodb-prod
        ports:
        - containerPort: 27017
        resources:
          limits:
            ephemeral-storage: 3Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: roseflix-mongodb-service
spec:
  selector:
    app: roseflix-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
