apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: https://public.ecr.aws/z2m4y8s8/dp1001:roseflix-mongodb-prod
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-volume
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-volume
        persistentVolumeClaim:
          claimName: mongodb-persistent-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: roseflix-mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
